import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
  unlinkSync,
} from 'node:fs';
import { join } from 'node:path';
import { ObeliskError } from '../../shared/errors';
import type {
  AgentName,
  TestPlan,
  TestPlanBlock,
  TestPlanFrontmatter,
  TestPlanScope,
  TestPlanSummary,
} from '../../shared/types';
import { countCases, parsePlanFile, serializePlan } from './parse';

/** Subdir under the user's repo where plans live. Mirrors the existing playbook layout. */
export const PLAN_SUBDIR = ['qa', 'test-plans'] as const;

export function plansDir(repoPath: string): string {
  return join(repoPath, ...PLAN_SUBDIR);
}

function ensureDir(path: string): void {
  mkdirSync(path, { recursive: true });
}

export function planFilePath(repoPath: string, planId: string): string {
  return join(plansDir(repoPath), `${planId}.md`);
}

export function listPlans(repoPath: string, agentName?: AgentName): TestPlanSummary[] {
  const dir = plansDir(repoPath);
  if (!existsSync(dir)) return [];
  const files = readdirSync(dir).filter((f) => f.endsWith('.md'));
  const out: TestPlanSummary[] = [];
  for (const f of files) {
    const full = join(dir, f);
    let plan: TestPlan;
    try {
      plan = readPlanFromFile(full);
    } catch {
      continue;
    }
    if (agentName && !plan.frontmatter.agentNames.includes(agentName)) continue;
    out.push({
      id: plan.frontmatter.id,
      name: plan.frontmatter.name,
      scope: plan.frontmatter.scope,
      feature: plan.frontmatter.feature,
      agentNames: plan.frontmatter.agentNames,
      caseCount: plan.caseCount,
      generatedAt: plan.frontmatter.generatedAt,
      updatedAt: plan.updatedAt,
    });
  }
  out.sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1));
  return out;
}

export function getPlan(repoPath: string, planId: string): TestPlan {
  const path = planFilePath(repoPath, planId);
  if (!existsSync(path)) {
    throw new ObeliskError('NOT_FOUND', `test plan '${planId}' not found`);
  }
  return readPlanFromFile(path);
}

function readPlanFromFile(path: string): TestPlan {
  const raw = readFileSync(path, 'utf8');
  const parsed = parsePlanFile(raw);
  const stat = statSync(path);
  return {
    frontmatter: parsed.frontmatter,
    blocks: parsed.blocks,
    caseCount: countCases(parsed.blocks),
    filePath: path,
    updatedAt: stat.mtime.toISOString(),
  };
}

export interface SavePlanInput {
  repoPath: string;
  planId: string;
  blocks: TestPlanBlock[];
  /** Allow renaming via save without forcing a separate IPC round-trip. */
  name?: string;
  /** Switch which QA agents this plan applies to. Empty list is rejected. */
  agentNames?: AgentName[];
  /**
   * Override the plan's feature binding. Used by the Coverage screen's
   * "Attach existing plan" dropdown so a plan that lacks `frontmatter.feature`
   * (created before the Coverage radar existed) can be retroactively pinned
   * to a feature label. Setting this also flips `scope` to `'feature'`.
   * Pass `null` to clear (binds to whole-app).
   */
  feature?: string | null;
}

export function savePlan(input: SavePlanInput): TestPlan {
  const path = planFilePath(input.repoPath, input.planId);
  if (!existsSync(path)) {
    throw new ObeliskError('NOT_FOUND', `test plan '${input.planId}' not found`);
  }
  const existing = readPlanFromFile(path);
  const nextAgents =
    input.agentNames && input.agentNames.length > 0
      ? dedupeAgents(input.agentNames)
      : existing.frontmatter.agentNames;
  const featureChanged = input.feature !== undefined;
  const nextFeature = featureChanged ? input.feature?.trim() || null : existing.frontmatter.feature;
  const nextScope = featureChanged
    ? nextFeature
      ? ('feature' as const)
      : ('whole-app' as const)
    : existing.frontmatter.scope;
  const next: TestPlanFrontmatter = {
    ...existing.frontmatter,
    name: input.name?.trim() || existing.frontmatter.name,
    agentNames: nextAgents,
    scope: nextScope,
    feature: nextFeature,
    version: existing.frontmatter.version + 1,
  };
  ensureDir(plansDir(input.repoPath));
  writeFileSync(path, serializePlan(next, input.blocks), 'utf8');
  return readPlanFromFile(path);
}

function dedupeAgents(list: AgentName[]): AgentName[] {
  const seen = new Set<string>();
  const out: AgentName[] = [];
  for (const a of list) {
    if (seen.has(a)) continue;
    seen.add(a);
    out.push(a);
  }
  return out;
}

/**
 * Every QA agent can run a plan by default. The plan author picks the
 * "primary" agent (used for id-naming + the generation prompt), but all
 * three QA agents land enabled in `agentNames` so the user doesn't have
 * to manually toggle chips before they can dispatch from any of them.
 */
export const DEFAULT_PLAN_AGENTS: AgentName[] = ['qa-hunter', 'manual-qa', 'ios-qa-pilot'];

export interface CreatePlanInput {
  repoPath: string;
  /**
   * Primary agent for this plan — used to compute the file id (so plans
   * generated by different agents don't collide) and to flavor the
   * default name. The plan is written with every QA agent enabled in
   * `agentNames` so users can dispatch from any of them; pass
   * `agentNames` to narrow that list explicitly.
   */
  agentName: AgentName;
  /** Override the default "all QA agents" seed list. */
  agentNames?: AgentName[];
  scope: TestPlanScope;
  featureName?: string;
  blocks: TestPlanBlock[];
  generatedBy: TestPlanFrontmatter['generatedBy'];
}

export function createPlan(input: CreatePlanInput): TestPlan {
  ensureDir(plansDir(input.repoPath));
  const id = nextPlanId(input);
  const agents =
    input.agentNames && input.agentNames.length > 0
      ? dedupeAgents(input.agentNames)
      : [...DEFAULT_PLAN_AGENTS];
  const fm: TestPlanFrontmatter = {
    id,
    name: defaultPlanName(input),
    scope: input.scope,
    feature: input.scope === 'feature' ? (input.featureName?.trim() ?? null) : null,
    agentNames: agents,
    generatedAt: new Date().toISOString(),
    generatedBy: input.generatedBy,
    version: 1,
  };
  const path = planFilePath(input.repoPath, id);
  writeFileSync(path, serializePlan(fm, input.blocks), 'utf8');
  return readPlanFromFile(path);
}

export function deletePlan(repoPath: string, planId: string): void {
  const path = planFilePath(repoPath, planId);
  if (!existsSync(path)) {
    throw new ObeliskError('NOT_FOUND', `test plan '${planId}' not found`);
  }
  unlinkSync(path);
}

function defaultPlanName(input: CreatePlanInput): string {
  if (input.scope === 'feature' && input.featureName?.trim()) {
    return `${capitalize(input.featureName.trim())} sweep`;
  }
  return 'Full app sweep';
}

function nextPlanId(input: CreatePlanInput): string {
  const base =
    input.scope === 'feature' && input.featureName?.trim()
      ? `feature-${slugify(input.featureName)}`
      : 'full-app';
  // Append agent suffix when the agent isn't qa-hunter so plans don't collide.
  const suffix = input.agentName === 'qa-hunter' ? '' : `-${slugify(input.agentName)}`;
  let candidate = `${base}${suffix}`;
  let n = 2;
  while (existsSync(planFilePath(input.repoPath, candidate))) {
    candidate = `${base}${suffix}-${n}`;
    n += 1;
  }
  return candidate;
}

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '')
      .slice(0, 48) || 'plan'
  );
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
